version: "3.7"
services:
  gluetun:
    image: docker.io/qmcgaw/gluetun
    expose:
      - 8000     # Control Server
      - 8888/tcp # HTTP proxy
      - 8888/udp
    environment:
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP}
      WIREGUARD_ENDPOINT_PORT: 51820
      WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY}
      WIREGUARD_ADDRESS: 10.80.239.2/24
      HEALTH_VPN_DURATION_INITIAL: 120s
      HTTPPROXY: "on"
      HTTPPROXY_STEALTH: "on"
      TZ: ${TZ}
      DOT: "off"
      HTTP_CONTROL_SERVER_LOG: "off"
      FIREWALL: "on"
      UPDATER_PERIOD: 3h
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    cap_add:
      - NET_ADMIN
    volumes:
      # To use wireguard kernel mode.
      - /lib/modules:/lib/modules:ro
    healthcheck:
      interval: 30s
    devices:
      - /dev/net/tun

  hotspot:
    build:
      context: hotspot
    image: hotspot
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      INTERFACE: wlan0
      OUTGOINGS: tun0
      WPA_PASSPHRASE: ${ADMIN_PSK}
      SSID: vpn-hotspot-ua
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "test $(wget -qO- http://ifconfig.me/) = $WIREGUARD_ENDPOINT_IP"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s